# Generated by Django 2.2.4 on 2019-09-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190904_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
