# Generated by Django 2.2.4 on 2019-08-20 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id_forum', models.AutoField(primary_key=True, serialize=False)),
                ('forum_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_desc', models.TextField()),
            ],
            options={
                'db_table': 'forum_category',
            },
        ),
        migrations.CreateModel(
            name='ForumMember',
            fields=[
                ('id_forum_member', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('id_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='forum.Forum')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_member',
            },
        ),
        migrations.CreateModel(
            name='ForumDiscussion',
            fields=[
                ('id_discussion', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('is_hide', models.BooleanField(default=False)),
                ('id_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_discussion', to='forum.Forum')),
                ('id_forum_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ForumMember')),
            ],
            options={
                'db_table': 'forum_discussion',
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_category', to='forum.ForumCategory'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id_comments', models.AutoField(primary_key=True, serialize=False)),
                ('id_discussion', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_hide', models.BooleanField(default=False)),
                ('comments_date', models.DateTimeField(auto_now_add=True)),
                ('id_forum_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ForumMember')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
