# Generated by Django 2.2.4 on 2019-08-29 09:58

from django.db import migrations, models
import trisakti.promotions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id_promotion', models.CharField(default=trisakti.promotions.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('url_banner', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'promotion',
            },
        ),
    ]
