# Generated by Django 2.2.4 on 2019-09-03 11:05

from django.db import migrations, models
import trisakti.promotions.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20190830_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='url_banner',
            field=models.ImageField(upload_to=trisakti.promotions.models.path_and_rename),
        ),
    ]
