# Generated by Django 2.2.4 on 2019-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20190903_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
