# Generated by Django 2.2.4 on 2019-09-03 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trisakti.jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id_category', models.CharField(default=trisakti.jobs.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'career_category',
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id_job', models.CharField(default=trisakti.jobs.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancy', to='jobs.CareerCategory')),
            ],
            options={
                'db_table': 'job_vacancy',
            },
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('trx_job', models.CharField(default=trisakti.jobs.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('body_messages', models.TextField()),
                ('attachment_code', models.CharField(default=trisakti.jobs.models.hex_uuid, max_length=250, unique=True)),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('id_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_apply', to='jobs.JobVacancy')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_job', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'job_apply',
            },
        ),
        migrations.CreateModel(
            name='AttachmentJobApply',
            fields=[
                ('id_attachment', models.CharField(default=trisakti.jobs.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('attachment_name', models.CharField(max_length=250)),
                ('url_attachment', models.FileField(upload_to=trisakti.jobs.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])])),
                ('attachment_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attach_job', to='jobs.JobApply', to_field='attachment_code')),
            ],
            options={
                'db_table': 'attacment_job_apply',
            },
        ),
    ]
