# Generated by Django 2.2.4 on 2019-09-13 09:08

import django.core.validators
from django.db import migrations, models
import trisakti.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190913_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercategory',
            name='url_image',
            field=models.FileField(default=1, upload_to=trisakti.jobs.models.path_category, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
    ]
