# Generated by Django 2.2.4 on 2019-09-13 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_careercategory_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='username',
            field=models.ForeignKey(db_column='username', default='galeeh', on_delete=django.db.models.deletion.CASCADE, related_name='username_vacancy', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
