# Generated by Django 2.2.4 on 2019-09-14 14:04

import django.core.validators
from django.db import migrations, models
import trisakti.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobvacancy_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='url_attachment',
            field=models.FileField(default=1, upload_to=trisakti.jobs.models.path_attachment, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
    ]
