# Generated by Django 2.2.4 on 2019-09-27 07:46

import django.core.validators
from django.db import migrations, models
import trisakti.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190914_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careercategory',
            name='url_image',
            field=models.FileField(blank=True, null=True, upload_to=trisakti.jobs.models.path_category, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='experience_job',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='function_job',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='required_skill',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_joblist',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='type_job',
            field=models.CharField(max_length=250),
        ),
    ]
